name: Continuous Integration
on: 
  push: 
    branches:
      - Workshop7

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 5.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Dotnet build
      run: dotnet build --configuration Release

    - name: Dotnet test
      run: dotnet test

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Typescript install
      run: npm ci
      working-directory: ./workshop_8.Web

    - name: Typescript build
      run: npm run build 
      working-directory: ./workshop_8.Web

    - name: Typescript test
      run: npm run test
      working-directory: ./workshop_8.Web

    - name: Docker Image Build
      run: docker build -t joebawn/workshop_8 .
      working-directory: .

    - name: Docker Login
      env: 
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }} 
      run: echo $DOCKER_HUB_TOKEN | docker login --username joebawn --password-stdin
      working-directory: .
    
    - name: Docker Image Push
      run: docker push joebawn/workshop_8:workshop-8-app
      working-directory: .